### ISSUE TITLE
連絡：Scene0/3 .unity の更新

### ISSUE THREAD

**Issue by kozaru** [wonder-shooter/display#8]
OKやったらクローズしてください。

もろもろマージしました。

---

マージの時にコンフリクトがおこった下記のファイルを、a4c43dc に合わせて、マージ後、をアニメーションいれて更新しました。

Scene0.unity
Scene3.unity

---

33a8402
2e6dd69

でguidが変わるので、これを下記のコミットでこちらからのpushをignoreしました。

0c91392

---

気になること
動かすと下記のエラーがでてました。

DllNotFoundException: openvr_api
Valve.VR.OpenVR.InitInternal (Valve.VR.EVRInitError& peError, EVRApplicationType eApplicationType) (at Assets/_Libs/SteamVR/Plugins/openvr_api.cs:4543)
Valve.VR.OpenVR.Init (Valve.VR.EVRInitError& peError, EVRApplicationType eApplicationType) (at Assets/_Libs/SteamVR/Plugins/openvr_api.cs:4969)
SteamVR_RenderModel+RenderModelInterfaceHolder.get_instance () (at Assets/_Libs/SteamVR/Scripts/SteamVR_RenderModel.cs:83)
SteamVR_RenderModel.SetModel (System.String renderModelName) (at Assets/_Libs/SteamVR/Scripts/SteamVR_RenderModel.cs:281)
SteamVR_RenderModel.Update () (at Assets/_Libs/SteamVR/Scripts/SteamVR_RenderModel.cs:674)

Couldn't open /Applications/Unity1.1/Unity.app/Contents/UnityExtensions/Unity/VR/OSXUniversal/OVRPlugin.bundle/Contents/MacOS/OVRPlugin, error: dlopen(/Applications/Unity1.1/Unity.app/Contents/UnityExtensions/Unity/VR/OSXUniversal/OVRPlugin.bundle/Contents/MacOS/OVRPlugin, 2): Library not loaded: @rpath/LibOVRRT_0.framework/Versions/5/LibOVRRT_0
  Referenced from: /Applications/Unity1.1/Unity.app/Contents/UnityExtensions/Unity/VR/OSXUniversal/OVRPlugin.bundle/Contents/MacOS/OVRPlugin
  Reason: image not found

Oculus Plugin could not be loaded.

**Comment by kamiyam** [comment]
↑ Viveが動いていないのでOpenVRのエラーが出ているのだと思います
